### ISSUE TITLE
Modify the header file to fix the error during compilation

### ISSUE THREAD

**Issue by scottpedia** [polarpiberry/MPU6050-C-CPP-Library-for-Raspberry-Pi#1]
The header file should include the i2c library for pi with "c" external identifier like below:
`extern "c"{
#include <linux/i2c-dev>
}`
Or the compiler will be unable to find and include the c library in a cpp program.(errors below:

> g++ -fPIC -c MPU6050.cpp -o MPU6050.o
MPU6050.cpp: In constructor ‘MPU6050::MPU6050(int8_t)’:
MPU6050.cpp:37:51: error: ‘i2c_smbus_write_byte_data’ was not declared in this scope
  i2c_smbus_write_byte_data(f_dev, 0x6b, 0b00000000); //Take MPU6050 out of sleep mode - see Register Map
                                                   ^
MPU6050.cpp: In member function ‘void MPU6050::getGyroRaw(float, float, float)’:
MPU6050.cpp:54:50: error: ‘i2c_smbus_read_byte_data’ was not declared in this scope
  int16_t X = i2c_smbus_read_byte_data(f_dev, 0x43) << 8 | i2c_smbus_read_byte_data(f_dev, 0x44); //Read X registers
                                                  ^
MPU6050.cpp: In member function ‘void MPU6050::getAccelRaw(float, float, float)’:
MPU6050.cpp:70:50: error: ‘i2c_smbus_read_byte_data’ was not declared in this scope
  int16_t X = i2c_smbus_read_byte_data(f_dev, 0x3b) << 8 | i2c_smbus_read_byte_data(f_dev, 0x3c); //Read X registers
                                                  ^
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by alex-mous** [comment]
Thanks for the heads up and fix!
