### ISSUE TITLE
Angles are drifting

### ISSUE THREAD

**Issue by maxomous** [polarpiberry/MPU6050-C-CPP-Library-for-Raspberry-Pi#10]
After running the example, the angles seem to be incrementally changing each read when the MPU6050 is stationary.
They seem to wrap around (e.g. here between -27 to -21).

I thought perhaps setting calc_yaw to false might help but same issue. I have also disconnected any other devices but still see the same issue.

I am using a raspberry pi 3b.

Below is the output from the example file:

> Current angle around the roll axis: -25.4695
> Current angle around the pitch axis: -25.9261
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -25.0986
> Current angle around the pitch axis: -26.9491
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -24.727
> Current angle around the pitch axis: -27.9685
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -24.3882
> Current angle around the pitch axis: -22.6544
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -24.0298
> Current angle around the pitch axis: -23.6461
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -23.6671
> Current angle around the pitch axis: -24.6364
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -23.2543
> Current angle around the pitch axis: -25.7628
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -22.8914
> Current angle around the pitch axis: -26.7387
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -22.5377
> Current angle around the pitch axis: -27.7226
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -22.1756
> Current angle around the pitch axis: -22.6529
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -21.8173
> Current angle around the pitch axis: -23.6487
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -21.4295
> Current angle around the pitch axis: -24.7079
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -21.0691
> Current angle around the pitch axis: -25.7156
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -26.6888
> Current angle around the pitch axis: -26.7705
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -26.3078
> Current angle around the pitch axis: -27.825
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -25.9559
> Current angle around the pitch axis: -22.6705
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -25.5976
> Current angle around the pitch axis: -23.6501
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -25.227
> Current angle around the pitch axis: -24.669
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -24.8443
> Current angle around the pitch axis: -25.7288
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -24.5081
> Current angle around the pitch axis: -26.6652
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -24.1208
> Current angle around the pitch axis: -27.7215
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -23.7356
> Current angle around the pitch axis: -22.6929
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -23.3655
> Current angle around the pitch axis: -23.7046
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -23.0154
> Current angle around the pitch axis: -24.6873
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -22.6472
> Current angle around the pitch axis: -25.7079
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -22.2735
> Current angle around the pitch axis: -26.7372
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -21.9365
> Current angle around the pitch axis: -27.6659
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -21.5539
> Current angle around the pitch axis: -22.5427
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -21.1856
> Current angle around the pitch axis: -23.5513
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -26.9229
> Current angle around the pitch axis: -24.5942
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -26.5378
> Current angle around the pitch axis: -25.6452
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -26.181
> Current angle around the pitch axis: -26.6323
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -25.8149
> Current angle around the pitch axis: -27.639
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -25.4375
> Current angle around the pitch axis: -22.5403
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -25.1064
> Current angle around the pitch axis: -23.4519
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -24.7316
> Current angle around the pitch axis: -24.4912
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -24.3729
> Current angle around the pitch axis: -25.4876
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -24.0183
> Current angle around the pitch axis: -26.4669
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -23.6153
> Current angle around the pitch axis: -27.593
> Current angle around the yaw axis: 0
> Current angle around the roll axis: -23.2599
> Current angle around the pitch axis: -22.4995
> Current angle around the yaw axis: 0
> Accelerometer Readings: X: 0.326, Y: 0.41, Z: 0.804
> Gyroscope Readings: X: 1.412, Y: -4.069, Z: 1.267

thanks in advance

**Comment by maxomous** [comment]
Interestingly, I have just notices that the drift is considerably less when the pcb is positioned vertically...

**Comment by alex-mous** [comment]
Yes, the MPU6050 is prone to drift unfortunately. You may be able to help with using the DMP, but the code here doesn't utilize that function of the MPU6050 - I believe there is another slightly larger library available which does use DMP.
