### ISSUE TITLE
MPU6050.o: undefined reference to symbol 'i2c_smbus_write_byte_data'

### ISSUE THREAD

**Issue by Mervus** [polarpiberry/MPU6050-C-CPP-Library-for-Raspberry-Pi#7]
I installed libi2c-dev, i2c-tools, and libi2c0.
when i try to compile it with:
 g++ -o MPU6050 MPU6050.o -L. libMPU6050.so
 
 it returns:
/usr/bin/ld: MPU6050.o: undefined reference to symbol 'i2c_smbus_write_byte_data'
/usr/bin/ld: //lib/arm-linux-gnueabihf/libi2c.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
i also ran the makefile.
Raspberry lite os.
I think i messed up somewhere but i cant tell where. I am sorry if this isnt a real issue.

**Comment by alex-mous** [comment]
When you installed libi2c-dev, i2c-tools, and libi2c0, did you encounter any errors? Did you enable i2c in `raspi-config`? Have you had any success with any other i2c-based programs?

When running `make`, did you use `make all`? If so, did it return the same output? And, if you didn't run it first, did you make sure to run `make clean` before trying again?

**Comment by Mervus** [comment]
I enabled `raspi-config` but i didnt use `make all` and `make clean`. 

I opened raspi-config again and enabled in Interface options I2C.
Tryed to compile it. Same error shown.
Restarted it and tryed it again.

I had no problems while installing libi2c.dev, i2c-tools, and libi2c0.
apt-get install libi2c-dev libi2c-dev  libi2c0
Reading package lists... Done
Building dependency tree
Reading state information... Done
libi2c-dev is already the newest version (4.1-1).
libi2c0 is already the newest version (4.1-1).
0 upgraded, 0 newly installed, 0 to remove and 23 not upgraded.

I never tryed other i2c-based programs.
So i ran make clean then make all and it worked properly then while compiling it with
`g++ -o MPU6050 MPU6050.cpp MPU6050.h`
it returned:
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/8/../../../arm-linux-gnueabihf/crt1.o: in function `_start':
(.text+0x34): undefined reference to `main'
/usr/bin/ld: /tmp/ccNjxnjb.o: in function `MPU6050::MPU6050(signed char, bool)':
MPU6050.cpp:(.text+0x100): undefined reference to `i2c_smbus_write_byte_data'
/usr/bin/ld: MPU6050.cpp:(.text+0x118): undefined reference to `i2c_smbus_write_byte_data'
/usr/bin/ld: MPU6050.cpp:(.text+0x130): undefined reference to `i2c_smbus_write_byte_data'
/usr/bin/ld: MPU6050.cpp:(.text+0x148): undefined reference to `i2c_smbus_write_byte_data'
/usr/bin/ld: MPU6050.cpp:(.text+0x160): undefined reference to `i2c_smbus_write_byte_data'
/usr/bin/ld: /tmp/ccNjxnjb.o:MPU6050.cpp:(.text+0x178): more undefined references to `i2c_smbus_write_byte_data' follow
/usr/bin/ld: /tmp/ccNjxnjb.o: in function `MPU6050::getGyroRaw(float*, float*, float*)':
MPU6050.cpp:(.text+0x33c): undefined reference to `i2c_smbus_read_byte_data'
/usr/bin/ld: MPU6050.cpp:(.text+0x35c): undefined reference to `i2c_smbus_read_byte_data'
/usr/bin/ld: MPU6050.cpp:(.text+0x380): undefined reference to `i2c_smbus_read_byte_data'
/usr/bin/ld: MPU6050.cpp:(.text+0x3a0): undefined reference to `i2c_smbus_read_byte_data'
/usr/bin/ld: MPU6050.cpp:(.text+0x3c4): undefined reference to `i2c_smbus_read_byte_data'
/usr/bin/ld: /tmp/ccNjxnjb.o:MPU6050.cpp:(.text+0x3e4): more undefined references to `i2c_smbus_read_byte_data' follow
/usr/bin/ld: /tmp/ccNjxnjb.o: in function `std::thread::thread<void (MPU6050::*)(), MPU6050*, void>(void (MPU6050::*&&)(), MPU6050*&&)':
MPU6050.cpp:(.text._ZNSt6threadC2IM7MPU6050FvvEJPS1_EvEEOT_DpOT0_[_ZNSt6threadC5IM7MPU6050FvvEJPS1_EvEEOT_DpOT0_]+0xac): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status

**Comment by alex-mous** [comment]
I believe that is a linking issue with the i2c library. I think the issue is that the object files already exist, so despite you trying new things, it still fails. Try running `make clean` and then `make all`, instead of using the compiling commands directly.
