### ISSUE TITLE
Can't run the Example.cpp file

### ISSUE THREAD

**Issue by IsmailHamzaoui** [polarpiberry/MPU6050-C-CPP-Library-for-Raspberry-Pi#8]
I tried to run Example.cpp file with the command:
`sudo ./Example.cpp`
and the error message was:
`sudo: ./Example.cpp: command not found
`

**Comment by alex-mous** [comment]
`.cpp` files are not executable. To run the example code, you have to compile the source code first. Please run `make example` and then `sudo ./Example` to run the example.
