### ISSUE TITLE
When I run `make` I get `MPU6050.h:46:11: fatal error: i2c/smbus.h: No such file or directory`

### ISSUE THREAD

**Issue by MotorCityCobra** [polarpiberry/MPU6050-C-CPP-Library-for-Raspberry-Pi#9]
$ make  

g++ -c MPU6050.cpp -o MPU6050.o -fPIC -Wall
In file included from MPU6050.cpp:6:0:
MPU6050.h:46:11: fatal error: i2c/smbus.h: No such file or directory
  #include <i2c/smbus.h>
           ^~~~~~~~~~~~~
compilation terminated.
Makefile:15: recipe for target 'MPU6050.o' failed
make: *** [MPU6050.o] Error 1

**Comment by Acca-Zeta** [comment]
On raspbian stretch it gave me the same error. on raspbian buster it is working fine.

**Comment by alex-mous** [comment]
Do you have libi2c-dev installed?
